# Header
menu:
  Blog: /#blog
  About: /about
  Archive: /archive

# Site favicon
favicon: images/favicon.jpg

# Site logo
# logo: /avatar.png

# Enable Mathjax
mathjax: true

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false